### ISSUE TITLE
Add functionality to respect Instance Protection - Scale In Protection

### ISSUE THREAD

**Issue by ichekrygin** [hjacobs/kube-aws-autoscaler#29]
### Overview

User can enable `Instance Protection` -> `Scale In Protection` on any instance w/in a given `ASG` [More details on Instance Protection](http://docs.aws.amazon.com/autoscaling/latest/userguide/as-instance-termination.html#instance-protection)

### Problem
It appears the autoscaler does not respect `Instance Protection` and can request instance termination even if/when protection is enabled.

### Request
Modify autoscaler to "exclude" instances with enabled protection from the "pool" of instances which are subject for "scale-down" event.

**Comment by hjacobs** [comment]
@ichekrygin the autoscaler currently will only change the `DesiredCapacity` on the ASG, i.e. the instance protection "should work". Can you describe your exact use case and what the observed problem is?

**Comment by ichekrygin** [comment]
@hjacobs - sorry, I agree. This issue is most likely with our ASG Protection setup. I will investigate further.

**Comment by hjacobs** [comment]
@ichekrygin great thanks for the feedback!
