### ISSUE TITLE
Ignore certain ASGs

### ISSUE THREAD

**Issue by sgmiller** [hjacobs/kube-aws-autoscaler#50]
We've run into a problem recently where we have a heterogenous cluster consisting of some worker nodes (currently scaled by kube-aws-autoscaler) and an ASG of GPU instances that we don't want scaled by kube-aws-autoscaler, as we're trying to only keep enough nodes up to handle the available work.

It would be great to be able to ignore certain ASGs in k-a-a either by name or tag.

**Comment by hjacobs** [comment]
I think this is a duplicate of #26.
